import React, { useState } from "react";
import Head from "next/head";

import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiOutlineGithub,
} from "react-icons/ai";
import imag from "../public/jamal2.jpg";
import { BsFillMoonStarsFill } from "react-icons/bs";
import Image from "next/image";

const Header = ({ darkMode, setDarkMode }) => {
  return (
    <div>
      <Head>
        <title>JsPortfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className="min-h-screen">
        <nav className="py-10 mb-12 flex justify-between dark:text-white">
          <h1 className="font-burtons text-xl mr-2">developedbyjs</h1>
          <ul className="flex items-center">
            <li>
              <BsFillMoonStarsFill
                onClick={() => setDarkMode(!darkMode)}
                className=" cursor-pointer text-2xl"
              />
            </li>
            <li>
              <a
                className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8"
                href="https://drive.google.com/file/d/1-D_x4tQUiiwLWXzuP_LNXXkT6y_HFoZv/view?usp=share_link"
                target="_blank"
              >
                Resume
              </a>
            </li>
          </ul>
        </nav>
        <div className="text-center p-10 py-10">
          <h2 className="text-5xl py-2 text-teal-600 font-medium dark:text-teal-400 md:text-6xl">
            Jamal Shah
          </h2>
          <h3 className="text-2xl py-2 dark:text-white md:text-3xl">
            Web Developer.
          </h3>
          <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
            Software engineer providing services for programming and web
            development. Join me down below and let's get cracking!
          </p>
          <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
            <a
              href="https://twitter.com/Jamalshah811?t=d3Ul0ZjSynnEhj2LHdj7Hw&s=09"
              target="_blank"
            >
              <AiFillTwitterCircle />
            </a>
            <a
              href="https://www.linkedin.com/in/jamal-shah-0068b91a8"
              target="_blank"
            >
              <AiFillLinkedin />
            </a>
            <a href="https://github.com/Jamal811" target="_blank">
              <AiOutlineGithub />
            </a>
          </div>
          <div className=" m-auto bg-gradient-to-b from-teal-500 rounded-full relative overflow-hidden mt-20 md:h-96 md:w-96   w-[200px] h-[200px]">
            <Image src={imag} layout="fill" objectFit="cover" />
          </div>
        </div>
      </section>
    </div>
  );
};
export default Header;
